export const SITE = {
  website: "https://teamwardlabs.com/",
  author: "Joseph Ward",
  profile: "https://teamwardlabs.com/about/",
  desc: "From Programming to Distilling.",
  title: "Team Ward Labs",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/team-ward-labs/website/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Detroit",
} as const;
